### ISSUE TITLE
question: is there a way to use efb through another computer (browser maybe?)

### ISSUE THREAD

**Issue by g3nsvrv** [flybywiresim/efb#13] opened 2021-09-14 17:57 UTC
question: is there a way to use efb through another computer (browser maybe?) and integrate it with FS2020?

**Comment by johnhart96** [comment] 2023-05-16 20:04
I do not think this is possible yet. But I agree this would be a much desirable feature. I wish I had the expertise to write this in myself. Having both the MCDU and the EFB in a browser would be very cool!

**Comment by rgcouto** [comment] 2023-11-03 11:59
+1 for this feature! 

If any developer of the tool could give me some lights on the repo and this could likely be implemented, I would gladly join the (air)bus!

**Comment by FoxtrotSierra6829** [comment] 2024-01-31 22:44
duplicate of https://github.com/flybywiresim/aircraft/issues/6978

**Closed as not planned by FoxtrotSierra6829** 2024-01-31 22:44 UTC
